# Generated by Django 4.1.2 on 2022-10-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog_photo'),
        ),
    ]
