# Generated by Django 4.1.2 on 2022-10-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTV', '0002_blog_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to='blog_sound'),
        ),
    ]
